### ISSUE TITLE
Node emits new message instead of received one and drops additional data

### ISSUE THREAD

**Issue by lebaston100** [vtulluru/node-red-contrib-oracledb-mod#3]
After upgrading from version 0.5.8 to 0.6.0 the node no longer passes on the message that it received. This can be observed by looking at the debug out and also the message id of the node in the attached picture. This makes it impossible to work in the native node-red way of passing on messages because all the previous information is lost when passing though the node.
![oracle_problem](https://user-images.githubusercontent.com/26111114/109794987-b9026a00-7c16-11eb-887d-76a1fa584bd5.png)

**Comment by NetHans** [comment]
I can confirm this. For the use of the node, it is essential that the data from the input message is transferred to the output message (except for payload). Without a corresponding adjustment, the Node in version 0.6 cannot be used sensibly.

**Comment by vtulluru** [comment]
@recursivecodes , Can you please take a look at this issue?
Apparently, we are losing message context after querying.

**Comment by recursivecodes** [comment]
I'll take a look.

**Comment by recursivecodes** [comment]
I've pushed a fix for this. This is certainly not a regression, as the original message was never being passed along - but it is now.  @vtulluru - can you publish a new version to NPM?

**Comment by vtulluru** [comment]
I will check and push it shortly. Thanks!

**Comment by vtulluru** [comment]
Fix has been verified and published to npm. 

![image](https://user-images.githubusercontent.com/39396355/109905825-00174c00-7c65-11eb-9fc2-d3759973d69e.png)
