### ISSUE TITLE
Fix (for port validation function) is missing in v0.6.4 release

### ISSUE THREAD

**Issue by omrid01** [vtulluru/node-red-contrib-oracledb-mod#45]
Following pull-request #37 by @knolleary, a fix was provided in release v0.6.4, to ensure the port validation function in the config node returns a Boolean value (required by Node-red as of v3.1.x)

I have installed v0.6.4, but the problem persists. Yet, when I patch the source file manually, the issue is resolved. Maybe the fix (which appears in the v0.6.4 release notes), has been omitted from the release?

The manual fix was to edit the file 
**"&LT;Node-red home&GT;\node_modules\node-red-contrib-oracledb-mod\lib\oracledb.html"**
and replace
```return v == null || v.match(/^(\s*|\d+|null)$/);```
with
```return v == null || !!v.match(/^(\s*|\d+|null)$/);```

I am working on Windows, Node-red v3.1.3, Node-JS v20.10.0, NPM v10.2.3

**Comment by nauben** [comment]
It seems the issue was fixed in release 0.6.5. Thank you!
Unfortunately, npm does not seem to supply the new version for download (yet).
